# Generated by Django 3.2.12 on 2022-05-05 22:51

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0007_alter_shopuser_activation_key_expires"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 5, 7, 22, 51, 47, 24388, tzinfo=utc), verbose_name="актуальность ключа"
            ),
        ),
    ]
